// See https://aka.ms/new-console-template for more information
using static System.Console;

Console.WriteLine("Hello, World!");
Console.WriteLine("This console application is a top level program.");
Console.WriteLine("There is no namespace, no class and no using.");
Console.WriteLine("System namespace is imported implicitly.");
WriteLine("This line is generated by using static System.Console");

